# Generated by Django 5.2.15 on 2026-06-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_url', models.URLField(max_length=500)),
                ('issue_number', models.IntegerField(blank=True, null=True)),
                ('repo_full_name', models.CharField(max_length=255)),
                ('repo_url', models.URLField(blank=True, max_length=500)),
                ('installation_id', models.CharField(blank=True, max_length=100)),
                ('pr_url', models.URLField(blank=True, max_length=500, null=True)),
                ('pr_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('triage', 'Triage'), ('dispatch', 'Dispatch'), ('sandbox', 'Sandbox'), ('verification', 'Verification'), ('pr_creation', 'PR Creation'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('triage_result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='webhooks.webhookevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='agents_agen_status_7a307a_idx'), models.Index(fields=['repo_full_name', 'issue_number'], name='agents_agen_repo_fu_806c4d_idx')],
            },
        ),
    ]
