import logging
import os

import httpx

from celery import shared_task

logger = logging.getLogger(__name__)


@shared_task(
    bind=True,
    max_retries=2,
    default_retry_delay=30,
    name="workers.tasks.pr_creation.create_pull_request",
)
def create_pull_request(self, fix_result: dict, repo_info: dict) -> dict:
    """Create a draft pull request on GitHub via the API."""
    logger.info(
        "Creating PR — repo=%s/%s branch=%s",
        repo_info.get("owner", "?"),
        repo_info.get("repo", "?"),
        fix_result.get("branch", "?"),
    )
    try:
        github_token = os.getenv("GITHUB_TOKEN") or os.getenv("GITHUB_APP_PRIVATE_KEY", "")
        owner = repo_info.get("owner", "")
        repo = repo_info.get("repo", "")
        branch = fix_result.get("branch", "")
        title = fix_result.get("title", "STAS: Automated fix")
        body = fix_result.get("body", "This PR was automatically generated by STAS.")
        base_branch = repo_info.get("base_branch", "main")

        if github_token and owner and repo and branch:
            with httpx.Client() as client:
                resp = client.post(
                    f"https://api.github.com/repos/{owner}/{repo}/pulls",
                    headers={
                        "Authorization": f"Bearer {github_token}",
                        "Accept": "application/vnd.github.v3+json",
                    },
                    json={
                        "title": title,
                        "body": body,
                        "head": branch,
                        "base": base_branch,
                        "draft": True,
                    },
                )
                if resp.status_code == 201:
                    pr_data = resp.json()
                    pr_url = pr_data.get("html_url", "")
                    pr_number = pr_data.get("number", 0)
                    logger.info("PR created — url=%s number=%d", pr_url, pr_number)
                    return {
                        "repo_info": repo_info,
                        "fix_result": fix_result,
                        "pr_url": pr_url,
                        "pr_number": pr_number,
                        "status": "created",
                        "success": True,
                    }
                else:
                    logger.error("GitHub API error — status=%s body=%s", resp.status_code, resp.text)
                    return {
                        "repo_info": repo_info,
                        "fix_result": fix_result,
                        "pr_url": None,
                        "status": "error",
                        "error": resp.text,
                        "success": False,
                    }
        else:
            logger.warning("Missing GitHub credentials or repo info — returning placeholder")
            return {
                "repo_info": repo_info,
                "fix_result": fix_result,
                "pr_url": None,
                "status": "placeholder",
                "success": False,
            }
    except Exception as exc:
        logger.error("PR creation failed — %s", exc, exc_info=True)
        raise self.retry(exc=exc)
