-- Rollback of 018_switch_to_supabase_uuid.sql: restore users.id to SERIAL INTEGER
BEGIN;

-- Drop FK constraints referencing users.id (must drop before altering types)
ALTER TABLE github_oauth_tokens        DROP CONSTRAINT IF EXISTS github_oauth_tokens_user_id_fkey;
ALTER TABLE github_installations       DROP CONSTRAINT IF EXISTS github_installations_user_id_fkey;
ALTER TABLE github_webhook_configs     DROP CONSTRAINT IF EXISTS github_webhook_configs_user_id_fkey;
ALTER TABLE run_feedback               DROP CONSTRAINT IF EXISTS run_feedback_user_id_fkey;
ALTER TABLE notification_preferences   DROP CONSTRAINT IF EXISTS notification_preferences_user_id_fkey;
ALTER TABLE notification_history       DROP CONSTRAINT IF EXISTS notification_history_user_id_fkey;

-- Preserve the UUID id values before converting users.id back to an integer serial
ALTER TABLE users ADD COLUMN IF NOT EXISTS supabase_uid VARCHAR(255) UNIQUE;
UPDATE users SET supabase_uid = id::text WHERE supabase_uid IS NULL;

ALTER TABLE users ALTER COLUMN id DROP DEFAULT;

-- Renumber users to fresh serial ids (original serial ids are not recoverable from UUIDs)
DO $$
DECLARE
  rec RECORD;
  next_id INTEGER := 1;
BEGIN
  FOR rec IN SELECT id FROM users ORDER BY id LOOP
    UPDATE users SET id = next_id WHERE id = rec.id;
    next_id := next_id + 1;
  END LOOP;
END $$;

ALTER TABLE users ALTER COLUMN id TYPE INTEGER;
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE users DROP COLUMN IF EXISTS supabase_uid;
DROP INDEX IF EXISTS idx_users_supabase_uid;

-- Convert FK columns from UUID back to INTEGER, remapping to the new serial ids
ALTER TABLE github_oauth_tokens ALTER COLUMN user_id TYPE INTEGER
  USING ((SELECT s.serial_id FROM (SELECT id, row_number() OVER (ORDER BY id)::int AS serial_id FROM users) s WHERE s.id = github_oauth_tokens.user_id));
ALTER TABLE github_installations ALTER COLUMN user_id TYPE INTEGER
  USING ((SELECT s.serial_id FROM (SELECT id, row_number() OVER (ORDER BY id)::int AS serial_id FROM users) s WHERE s.id = github_installations.user_id));
ALTER TABLE github_webhook_configs ALTER COLUMN user_id TYPE INTEGER
  USING ((SELECT s.serial_id FROM (SELECT id, row_number() OVER (ORDER BY id)::int AS serial_id FROM users) s WHERE s.id = github_webhook_configs.user_id));
ALTER TABLE run_feedback ALTER COLUMN user_id TYPE INTEGER
  USING ((SELECT s.serial_id FROM (SELECT id, row_number() OVER (ORDER BY id)::int AS serial_id FROM users) s WHERE s.id = run_feedback.user_id));
ALTER TABLE notification_preferences ALTER COLUMN user_id TYPE INTEGER
  USING ((SELECT s.serial_id FROM (SELECT id, row_number() OVER (ORDER BY id)::int AS serial_id FROM users) s WHERE s.id = notification_preferences.user_id));
ALTER TABLE notification_history ALTER COLUMN user_id TYPE INTEGER
  USING ((SELECT s.serial_id FROM (SELECT id, row_number() OVER (ORDER BY id)::int AS serial_id FROM users) s WHERE s.id = notification_history.user_id));

-- Re-create FK constraints referencing users.id
ALTER TABLE github_oauth_tokens        ADD CONSTRAINT github_oauth_tokens_user_id_fkey        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE github_installations       ADD CONSTRAINT github_installations_user_id_fkey       FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE github_webhook_configs     ADD CONSTRAINT github_webhook_configs_user_id_fkey     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE run_feedback               ADD CONSTRAINT run_feedback_user_id_fkey                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE notification_preferences   ADD CONSTRAINT notification_preferences_user_id_fkey    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE notification_history       ADD CONSTRAINT notification_history_user_id_fkey        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

COMMIT;
