export default function DPAPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
      <div className="text-center"><h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">Data Processing Agreement</h1><p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">Version: <strong>2026-06-01</strong></p></div>
      <div className="mt-12 space-y-8 text-sm text-gray-600 leading-relaxed">
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">1. Definitions</h2><ul className="mt-4 space-y-3"><li><strong>"Controller"</strong> — the customer who determines purposes of processing.</li><li><strong>"Processor"</strong> — STAS (Aimino Technologies) which processes data on behalf of Controller.</li><li><strong>"Personal Data"</strong> — information relating to an identified natural person.</li><li><strong>"Sub-processor"</strong> — third-party engaged to assist in processing.</li></ul></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">2. Processing of Personal Data</h2><p className="mt-4">2.1 Processor shall process data only on Controller's documented instructions. 2.2 Authorized persons are bound by confidentiality. 2.3 Processor implements appropriate technical and organizational security measures.</p></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">3. No Training on Customer Data</h2><p className="mt-4">3.1 Processor shall not use Customer Data for AI model training. 3.2 This applies to all models including third-party APIs. 3.3 Processor ensures third-party providers are contractually bound.</p></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">4. Data Retention and Deletion</h2><p className="mt-4">4.1 Data retained only for Agreement duration. 4.2 Upon termination, all data deleted within 30 days. 4.3 Written confirmation provided on request.</p></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">5. Sub-processors</h2><ul className="mt-4 space-y-2"><li><span className="text-brand-600 font-bold">•</span> GitHub, Inc. — repository hosting</li><li><span className="text-brand-600 font-bold">•</span> Stripe, Inc. — payment processing</li><li><span className="text-brand-600 font-bold">•</span> OpenAI / Anthropic — AI inference (no training)</li><li><span className="text-brand-600 font-bold">•</span> Railway / Fly.io — cloud infrastructure</li></ul></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">6. Security Measures</h2><ul className="mt-4 space-y-2"><li><span className="text-brand-600 font-bold">•</span> AES-256 encryption at rest, TLS 1.3 in transit</li><li><span className="text-brand-600 font-bold">•</span> Per-tenant data isolation via row-level security</li><li><span className="text-brand-600 font-bold">•</span> Ephemeral sandbox environments</li><li><span className="text-brand-600 font-bold">•</span> Access control with least privilege</li><li><span className="text-brand-600 font-bold">•</span> Incident response plan with 24-hour breach notification</li></ul></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">7. Data Breach Notification</h2><p className="mt-4">7.1 Processor shall notify Controller without undue delay upon becoming aware of a breach. 7.2 Processor shall provide sufficient information for regulatory obligations.</p></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">8. Governing Law</h2><p className="mt-4">This DPA shall be governed by the laws of the State of Delaware, United States.</p></section>
        <div className="rounded-xl border border-gray-200 bg-gray-50 p-6 text-center"><p className="text-sm text-gray-500">This DPA is incorporated into the STAS Terms of Service. By subscribing to a paid plan, you automatically accept this DPA. No separate signature required.</p></div>
      </div>
    </div>
  );
}
