export default function Privacy() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
      <div className="text-center"><h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">Data Privacy & Retention Policy</h1><p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">How SYNTARO handles, stores, and protects your data throughout its lifecycle.</p></div>
      <div className="mt-12 space-y-8">
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">Data We Collect</h2><ul className="mt-4 space-y-3 text-sm text-gray-600"><li className="flex gap-3"><span className="text-brand-600 font-bold">•</span><span><strong>Repository metadata</strong> — name, owner, installation ID</span></li><li className="flex gap-3"><span className="text-brand-600 font-bold">•</span><span><strong>Issue and PR content</strong> — titles, descriptions, code diffs (processed during fix runs)</span></li><li className="flex gap-3"><span className="text-brand-600 font-bold">•</span><span><strong>Account information</strong> — GitHub username, avatar URL, email</span></li><li className="flex gap-3"><span className="text-brand-600 font-bold">•</span><span><strong>Usage metrics</strong> — fix run counts, timestamps, pass/fail results</span></li></ul></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">Active Data Retention</h2><p className="mt-2 text-sm text-gray-600">While your subscription is active, we retain your data for the duration necessary to provide the service. You can view and export your data at any time from the dashboard.</p></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">Post-Cancellation Retention</h2><ul className="mt-4 space-y-3 text-sm text-gray-600"><li className="flex gap-3"><span className="text-brand-600 font-bold">•</span><span><strong>30-day grace period</strong> — data remains intact for reactivation</span></li><li className="flex gap-3"><span className="text-brand-600 font-bold">•</span><span><strong>Automatic purging</strong> — after 30 days, all customer data is permanently deleted</span></li><li className="flex gap-3"><span className="text-brand-600 font-bold">•</span><span><strong>Billing records</strong> — retained for legal/accounting purposes as required</span></li></ul></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">Requesting Data Deletion</h2><p className="mt-2 text-sm text-gray-600">Go to <strong>Settings → Data Privacy</strong> in your dashboard and click "Request Data Deletion". You can cancel within the 30-day window.</p></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">Third-Party Data Sharing</h2><p className="mt-2 text-sm text-gray-600">We do not sell, rent, or share your personal data. External services: <strong>GitHub</strong> (repo access), <strong>Stripe</strong> (payments), <strong>AI model providers</strong> (code snippets for fix generation, no training).</p></section>
        <section className="rounded-xl border border-gray-200 p-6"><h2 className="text-xl font-semibold text-gray-900">Data Portability</h2><p className="mt-2 text-sm text-gray-600">Export your data from the dashboard: fix run history, audit log, billing history, and repository connections.</p></section>
      </div>
    </div>
  );
}
