#!/bin/bash
# Quick deploy helper - shows code ready to copy
echo "═══════════════════════════════════════════════════"
echo "  AIMINO DASHBOARD — QUICK DEPLOY"
echo "═══════════════════════════════════════════════════"
echo ""
echo "📋 BƯỚC 1: Mở Google Sheet"
echo "   https://docs.google.com/spreadsheets/d/1Nf_H61D4GGq5aFlypAHlW_f1Uaso1c4OmJ9QRz5qRaY"
echo ""
echo "📋 BƯỚC 2: Click Extensions → Apps Script"
echo ""
echo "📋 BƯỚC 3: Copy Code.gs"
echo "   File location:"
echo "   /home/agent/Documents/hermes-agent/dashboard/Code.gs"
echo ""
echo "   Open in terminal:"
echo "   cat /home/agent/Documents/hermes-agent/dashboard/Code.gs | xclip -selection clipboard"
echo ""
echo "📋 BƯỚC 4: Create Index.html"
echo "   In Apps Script editor:"
echo "   - Click '+' next to Files"
echo "   - Select 'HTML'"
echo "   - Name: Index"
echo "   - Paste content from:"
echo "   /home/agent/Documents/hermes-agent/dashboard/Index.html"
echo ""
echo "📋 BƯỚC 5: Deploy"
echo "   - Click 'Deploy' → 'New deployment'"
echo "   - Select 'Web app'"
echo "   - Execute as: Me"
echo "   - Who has access: Anyone"
echo "   - Click 'Deploy'"
echo ""
echo "📋 BƯỚC 6: Initialize (first time only)"
echo "   - Select 'initializeSheets' from function dropdown"
echo "   - Click 'Run'"
echo "   - Authorize when prompted"
echo ""
echo "═══════════════════════════════════════════════════"
