-- Rollback 017_billing_teams
DROP TABLE IF EXISTS team_members CASCADE;
ALTER TABLE invites DROP COLUMN IF EXISTS monthly_limit_credits;
ALTER TABLE invites DROP COLUMN IF EXISTS team_id;
DROP TABLE IF EXISTS invites CASCADE;
DROP TABLE IF EXISTS repos CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS billing CASCADE;
